searchPath=/liquibase/changelog
changelogFile=liquibase-changelog.xml
driver=org.postgresql.Driver
url=jdbc:postgresql://<DB ENDPOINT>:5432/knowledge_db
username=knowledge_user
password=
liquibaseSchemaName=public
defaultSchemaName=knowledge